'use strict';

const express = require('express');
const crypto = require('node:crypto');
const { z } = require('zod');
const asyncHandler = require('../middleware/asyncHandler');
const { requireRole } = require('../middleware/auth');
const nodes = require('../../services/nodes');

const router = express.Router();
const agentRouter = express.Router();

const createSchema = z.object({
  name: z.string().trim().min(2).max(64),
  description: z.string().max(500).optional(),
  fqdn: z.string().trim().min(1).max(255),
  scheme: z.enum(['http', 'https']).default('https'),
  daemonPort: z.coerce.number().int().min(1).max(65535).default(8080),
  sftpPort: z.coerce.number().int().min(1).max(65535).default(2022),
  dataRoot: z.string().trim().min(1).max(500).default('/var/lib/craftly'),
});

function publicNode(node) {
  if (!node) return null;
  const { token_hash, ...safe } = node;
  delete safe.agent_token_cipher;
  return safe;
}

router.get('/nodes', requireRole('admin'), asyncHandler(async (req, res) => {
  await nodes.refreshLocalNode();
  nodes.markStale();
  res.json({ ok: true, nodes: nodes.listNodes().map(publicNode) });
}));

router.post('/nodes', requireRole('admin'), asyncHandler(async (req, res) => {
  const input = createSchema.parse(req.body);
  const result = nodes.createNode(input);
  res.status(201).json({
    ok: true,
    node: publicNode(result.node),
    token: result.token,
    warning: 'Store this token now. It is not displayed again.',
  });
}));

router.post('/nodes/:id/token', requireRole('admin'), (req, res) => {
  const result = nodes.rotateToken(req.params.id);
  if (!result) return res.status(404).json({ ok: false, error: 'Node not found' });
  res.json({ ok: true, node: publicNode(result.node), token: result.token, warning: 'Store this token now. It replaces the previous token.' });
});

router.post('/nodes/:id/enable', requireRole('admin'), (req, res) => {
  const node = nodes.setEnabled(req.params.id, true);
  if (!node) return res.status(404).json({ ok: false, error: 'Node not found' });
  res.json({ ok: true, node: publicNode(node) });
});

router.post('/nodes/:id/disable', requireRole('admin'), (req, res) => {
  const node = nodes.setEnabled(req.params.id, false);
  if (!node) return res.status(404).json({ ok: false, error: 'Node not found' });
  res.json({ ok: true, node: publicNode(node) });
});

router.delete('/nodes/:id', requireRole('admin'), (req, res) => {
  if (req.params.id === 'local') return res.status(400).json({ ok: false, error: 'The local node cannot be deleted.' });
  const result = nodes.removeNode(req.params.id);
  if (!result.changes) return res.status(404).json({ ok: false, error: 'Node not found' });
  res.json({ ok: true });
});

// Node-agent authentication is intentionally separate from browser/session auth.
// Remote agents authenticate with a bearer token generated by POST /api/nodes.
agentRouter.post('/node-agent/:id/heartbeat', asyncHandler(async (req, res) => {
  const auth = String(req.get('authorization') || '');
  const match = /^Bearer\s+(.+)$/i.exec(auth);
  const token = match ? match[1].trim() : '';
  const node = nodes.authenticateNode(req.params.id, token);
  if (!node) return res.status(401).json({ ok: false, error: 'Invalid node credentials' });

  const body = req.body && typeof req.body === 'object' ? req.body : {};
  const updated = nodes.recordHeartbeat(node.id, {
    docker: body.docker,
    dockerInfo: body.dockerInfo,
  });
  res.json({
    ok: true,
    node: publicNode(updated),
    serverTime: new Date().toISOString(),
    nonce: crypto.randomBytes(8).toString('hex'),
  });
}));

Object.assign(router, { agentRouter });
module.exports = router;
