'use strict';

// Auto-pause / auto-stop: freeze or shut down the server when nobody is
// online. The two features are mutually exclusive.

module.exports = [
  {
    key: 'ENABLE_AUTOPAUSE',
    scope: 'env',
    label: 'Auto-pause when empty',
    help: 'Freezes the Java process after the server has been idle, and wakes it the moment someone tries to connect. Requires the tick watchdog to be disabled (Max tick time = -1) or the server may be killed on resume.',
    type: 'boolean',
    default: false,
    mode: 'advanced',
    section: 'autopause',
    note: 'Incompatible with auto-stop',
    conflictsWith: 'ENABLE_AUTOSTOP',
    requiresRestart: true,
  },
  {
    key: 'AUTOPAUSE_TIMEOUT_EST',
    scope: 'env',
    label: 'Pause after last player leaves',
    help: 'Seconds to wait after the last player disconnects before pausing.',
    type: 'number',
    unit: 'seconds',
    default: 3600,
    min: 0,
    mode: 'advanced',
    section: 'autopause',
    requiresRestart: true,
  },
  {
    key: 'AUTOPAUSE_TIMEOUT_INIT',
    scope: 'env',
    label: 'Pause after start (no players)',
    help: 'Seconds to wait after server start before pausing if nobody has connected at all.',
    type: 'number',
    unit: 'seconds',
    default: 600,
    min: 0,
    mode: 'advanced',
    section: 'autopause',
    requiresRestart: true,
  },
  {
    key: 'AUTOPAUSE_TIMEOUT_KN',
    scope: 'env',
    label: 'Pause after port knock',
    help: 'Seconds to wait after a connection attempt (like a server-list ping) before pausing again if no player actually joins. Note: any external ping, including uptime monitors, wakes a paused server.',
    type: 'number',
    unit: 'seconds',
    default: 120,
    min: 0,
    mode: 'advanced',
    section: 'autopause',
    requiresRestart: true,
  },
  {
    key: 'AUTOPAUSE_PERIOD',
    scope: 'env',
    label: 'Pause check interval',
    help: 'How often, in seconds, the pause state machine checks whether it should pause. Waking up is instant and knock-driven, not tied to this interval.',
    type: 'number',
    unit: 'seconds',
    default: 10,
    min: 1,
    mode: 'advanced',
    section: 'autopause',
    requiresRestart: true,
  },
  {
    key: 'AUTOPAUSE_KNOCK_INTERFACE',
    scope: 'env',
    label: 'Knock network interface',
    help: 'Network interface watched for incoming connection attempts. Only change with host networking or unusual setups. The interface must exist inside the container, and "lo" does not work.',
    type: 'text',
    default: 'eth0',
    mode: 'advanced',
    section: 'autopause',
    requiresRestart: true,
  },
  {
    key: 'AUTOPAUSE_STATUS_RETRY_LIMIT',
    scope: 'env',
    label: 'Status retry limit',
    help: 'How many times the pause monitor retries reading the server status before giving up.',
    type: 'number',
    default: 10,
    min: 1,
    mode: 'advanced',
    section: 'autopause',
    requiresRestart: true,
  },
  {
    key: 'AUTOPAUSE_STATUS_RETRY_INTERVAL',
    scope: 'env',
    label: 'Status retry interval',
    help: 'Delay between status retries, e.g. 2s.',
    type: 'duration',
    default: '2s',
    mode: 'advanced',
    section: 'autopause',
    requiresRestart: true,
  },
  {
    key: 'DEBUG_AUTOPAUSE',
    scope: 'env',
    label: 'Auto-pause debug logging',
    help: 'Verbose logging of the auto-pause state machine, for troubleshooting why the server does or does not pause.',
    type: 'boolean',
    default: false,
    mode: 'advanced',
    section: 'autopause',
    requiresRestart: true,
  },
  {
    key: 'MAX_TICK_TIME',
    scope: 'env',
    prop: 'max-tick-time',
    label: 'Max tick time (watchdog)',
    help: 'Milliseconds a single tick may take before the watchdog kills the server (vanilla default 60000). Must be -1 (disabled) for auto-pause, since a paused tick looks endless to the watchdog. It is also common for heavy modpacks.',
    type: 'number',
    unit: 'ms',
    min: -1,
    mode: 'advanced',
    section: 'autopause',
    requiresRestart: true,
  },
  {
    key: 'ENABLE_AUTOSTOP',
    scope: 'env',
    label: 'Auto-stop when empty',
    help: 'Shuts the server down entirely (the container exits) after being idle. Unlike auto-pause, it does not wake automatically. You start it again from the panel. Do not combine it with auto-pause.',
    type: 'boolean',
    default: false,
    mode: 'advanced',
    section: 'autopause',
    note: 'Incompatible with auto-pause',
    conflictsWith: 'ENABLE_AUTOPAUSE',
    requiresRestart: true,
  },
  {
    key: 'AUTOSTOP_TIMEOUT_EST',
    scope: 'env',
    label: 'Stop after last player leaves',
    help: 'Seconds to wait after the last player disconnects before stopping the server.',
    type: 'number',
    unit: 'seconds',
    default: 3600,
    min: 0,
    mode: 'advanced',
    section: 'autopause',
    requiresRestart: true,
  },
  {
    key: 'AUTOSTOP_TIMEOUT_INIT',
    scope: 'env',
    label: 'Stop after start (no players)',
    help: 'Seconds to wait after server start before stopping if nobody has connected at all.',
    type: 'number',
    unit: 'seconds',
    default: 1800,
    min: 0,
    mode: 'advanced',
    section: 'autopause',
    requiresRestart: true,
  },
  {
    key: 'AUTOSTOP_PERIOD',
    scope: 'env',
    label: 'Stop check interval',
    help: 'How often, in seconds, the auto-stop state machine checks whether it should stop the server.',
    type: 'number',
    unit: 'seconds',
    default: 10,
    min: 1,
    mode: 'advanced',
    section: 'autopause',
    requiresRestart: true,
  },
  {
    key: 'DEBUG_AUTOSTOP',
    scope: 'env',
    label: 'Auto-stop debug logging',
    help: 'Verbose logging of the auto-stop state machine.',
    type: 'boolean',
    default: false,
    mode: 'advanced',
    section: 'autopause',
    requiresRestart: true,
  },
  {
    key: 'PAUSE_WHEN_EMPTY_SECONDS',
    scope: 'env',
    prop: 'pause-when-empty-seconds',
    label: 'Native pause when empty (1.21.2+)',
    help: 'Minecraft’s built-in pause: the game loop stops after the server has been empty this many seconds. On modern versions this is the recommended, simpler alternative to the container-level auto-pause above.',
    type: 'number',
    unit: 'seconds',
    min: 0,
    mode: 'advanced',
    section: 'autopause',
    note: 'Preferred over auto-pause (MC 1.21.2+)',
    requiresRestart: true,
  },
];
