'use strict';

// Server flavor & version: TYPE, VERSION, loader/build pins, plus a few
// container-level advanced knobs (timezone, UID/GID, setup-only mode).

module.exports = [
  {
    key: 'TYPE',
    scope: 'env',
    label: 'Server type',
    help: 'Which server platform to install and run. Changing this re-installs the server files on the next start; your world data is kept, but mods and plugins only work on matching types.',
    type: 'enum',
    default: 'VANILLA',
    options: [
      { value: 'VANILLA', label: 'Vanilla', desc: 'Official Mojang server. No mods or plugins, datapacks only.' },
      { value: 'PAPER', label: 'Paper', desc: 'High-performance Spigot fork; the most popular plugin server.' },
      { value: 'PURPUR', label: 'Purpur', desc: 'Paper fork focused on configurability and extra gameplay features.' },
      { value: 'PUFFERFISH', label: 'Pufferfish', desc: 'Optimized Paper fork aimed at large servers.' },
      { value: 'LEAF', label: 'Leaf', desc: 'Paper fork focused on performance and low-level optimizations.' },
      {
        value: 'FOLIA',
        label: 'Folia',
        desc: 'Paper with regionized multithreading; many plugins are not compatible.',
      },
      { value: 'SPIGOT', label: 'Spigot', desc: 'Legacy. Automated downloads no longer work; use Paper instead.' },
      {
        value: 'BUKKIT',
        label: 'CraftBukkit',
        desc: 'Legacy. Automated downloads no longer work; use Paper instead.',
      },
      {
        value: 'CANYON',
        label: 'Canyon',
        desc: 'CraftBukkit fork for Beta 1.7.3 only; health checks must be disabled.',
      },
      {
        value: 'FORGE',
        label: 'Forge',
        desc: 'MinecraftForge mod loader; versions before 1.18 need the Java 8 image.',
      },
      { value: 'NEOFORGE', label: 'NeoForge', desc: 'Modern community fork of Forge.' },
      { value: 'FABRIC', label: 'Fabric', desc: 'Lightweight mod loader; most mods also need the Fabric API mod.' },
      { value: 'QUILT', label: 'Quilt', desc: 'Fabric fork with its own loader and installer.' },
      {
        value: 'SPONGEVANILLA',
        label: 'SpongeVanilla',
        desc: 'Sponge plugin API on the vanilla server; uses its own plugin system.',
      },
      { value: 'CRUCIBLE', label: 'Crucible', desc: 'Forge + Bukkit hybrid for Minecraft 1.7.10 only.' },
      { value: 'MAGMA', label: 'Magma', desc: 'Legacy. A Forge and Paper hybrid; the project has ended.' },
      {
        value: 'MAGMA_MAINTAINED',
        label: 'Magma Maintained',
        desc: 'Community continuation of Magma; requires Forge version and release tag.',
      },
      { value: 'KETTING', label: 'Ketting', desc: 'Magma successor for Minecraft 1.20.1 and later.' },
      { value: 'MOHIST', label: 'Mohist', desc: 'Forge + Bukkit hybrid by MohistMC.' },
      { value: 'YOUER', label: 'Youer', desc: 'MohistMC hybrid combining NeoForge mods and Bukkit plugins.' },
      { value: 'BANNER', label: 'Banner', desc: 'MohistMC hybrid combining Fabric mods and Bukkit plugins.' },
      { value: 'ARCLIGHT', label: 'Arclight', desc: 'Multi-loader Bukkit hybrid (Forge, NeoForge, or Fabric).' },
      {
        value: 'LIMBO',
        label: 'Limbo',
        desc: 'Lightweight waiting-room server; ignores the Minecraft version setting.',
      },
      { value: 'NANOLIMBO', label: 'NanoLimbo', desc: 'Alternate lightweight limbo server.' },
      { value: 'CUSTOM', label: 'Custom JAR', desc: 'Bring your own server jar via the custom server URL/path field.' },
      {
        value: 'AUTO_CURSEFORGE',
        label: 'CurseForge modpack (auto)',
        desc: 'Fully automated CurseForge modpack install and upgrades; needs a CurseForge API key.',
      },
      {
        value: 'CURSEFORGE',
        label: 'CurseForge server pack (manual)',
        desc: 'Legacy. A manual server-pack runner; use the automated CurseForge type instead.',
      },
      {
        value: 'FTBA',
        label: 'Feed the Beast modpack',
        desc: 'Installs FTB App modpacks with their matching Forge automatically.',
      },
      {
        value: 'MODRINTH',
        label: 'Modrinth modpack',
        desc: 'Installs Modrinth (.mrpack) modpacks; no API key needed.',
      },
      { value: 'GTNH', label: 'GT New Horizons', desc: 'Dedicated type for the GTNH 1.7.10 modpack; needs 6 GB+ RAM.' },
    ],
    mode: 'simple',
    section: 'flavor',
    requiresRestart: true,
  },
  {
    key: 'VERSION',
    scope: 'env',
    label: 'Minecraft version',
    help: 'The Minecraft version to install, e.g. 1.20.4, or LATEST / SNAPSHOT to track a channel. With LATEST or SNAPSHOT, restarting the server upgrades it when a newer version is out.',
    type: 'text',
    default: 'LATEST',
    mode: 'simple',
    section: 'flavor',
    requiresRestart: true,
  },
  {
    key: 'EULA',
    scope: 'env',
    label: 'Mojang EULA accepted',
    help: 'The server refuses to start until Mojang’s End User License Agreement is accepted. The panel sets this automatically after you accept the EULA in the creation wizard.',
    type: 'boolean',
    mode: 'advanced',
    section: 'flavor',
    hidden: true,
    requiresRestart: true,
  },
  {
    key: 'PAPER_BUILD',
    scope: 'env',
    label: 'Paper build',
    help: 'Pins a specific PaperMC build number instead of the latest one for the chosen Minecraft version. Leave empty for the latest build.',
    type: 'text',
    mode: 'advanced',
    section: 'flavor',
    requiresRestart: true,
  },
  {
    key: 'PAPER_CHANNEL',
    scope: 'env',
    label: 'Paper release channel',
    help: 'Which PaperMC channel to download from. If a brand-new Minecraft version fails with "No build found ... with channel \'default\'", switch to experimental.',
    type: 'enum',
    options: [
      { value: 'default', label: 'Default (stable releases)' },
      { value: 'experimental', label: 'Experimental', desc: 'Pre-release builds for brand-new Minecraft versions.' },
    ],
    default: 'default',
    mode: 'advanced',
    section: 'flavor',
    requiresRestart: true,
  },
  {
    key: 'PURPUR_BUILD',
    scope: 'env',
    label: 'Purpur build',
    help: 'Pins a specific Purpur build for the chosen Minecraft version. Leave at LATEST unless you need to roll back a broken build.',
    type: 'text',
    default: 'LATEST',
    mode: 'advanced',
    section: 'flavor',
    requiresRestart: true,
  },
  {
    key: 'FORGE_VERSION',
    scope: 'env',
    label: 'Forge version',
    help: 'The Forge loader version, e.g. 14.23.5.2854 or "latest". When empty, the recommended Forge version for your Minecraft version is used.',
    type: 'text',
    mode: 'advanced',
    section: 'flavor',
    requiresRestart: true,
  },
  {
    key: 'NEOFORGE_VERSION',
    scope: 'env',
    label: 'NeoForge version',
    help: 'The NeoForge loader version: a specific version, "latest", or "beta". When empty, the latest non-beta version for your Minecraft version is used.',
    type: 'text',
    mode: 'advanced',
    section: 'flavor',
    requiresRestart: true,
  },
  {
    key: 'FABRIC_LOADER_VERSION',
    scope: 'env',
    label: 'Fabric loader version',
    help: 'Pins a specific Fabric loader version. Leave empty for the latest; most mods also need the Fabric API mod installed separately.',
    type: 'text',
    mode: 'advanced',
    section: 'flavor',
    requiresRestart: true,
  },
  {
    key: 'FABRIC_LAUNCHER_VERSION',
    scope: 'env',
    label: 'Fabric launcher version',
    help: 'Pins a specific version of the Fabric server launcher itself. Rarely needed. Leave it empty for the latest.',
    type: 'text',
    mode: 'advanced',
    section: 'flavor',
    requiresRestart: true,
  },
  {
    key: 'QUILT_LOADER_VERSION',
    scope: 'env',
    label: 'Quilt loader version',
    help: 'Pins a specific Quilt loader version. Leave empty for the latest.',
    type: 'text',
    mode: 'advanced',
    section: 'flavor',
    requiresRestart: true,
  },
  {
    key: 'CUSTOM_SERVER',
    scope: 'env',
    label: 'Custom server JAR',
    help: 'URL or container path of the server jar when the type is Custom. A URL is only downloaded once. To fetch a new copy, delete the jar from the server folder and restart.',
    type: 'text',
    mode: 'advanced',
    section: 'flavor',
    requiresRestart: true,
  },
  {
    key: 'javaTag',
    scope: 'panel',
    label: 'Java version (image tag)',
    help: 'Which Java runtime image the server runs on. Auto picks the right one for your Minecraft version, and for GT New Horizons, the newest Java the pinned pack version supports. Override only for special cases like old Forge (needs Java 8) or mods that break on newer Java. Forcing a GTNH server to Java 8 makes the image install GTNH’s legacy Java 8 server pack instead of the faster lwjgl3ify one.',
    type: 'enum',
    default: '',
    options: [
      {
        value: '',
        label: 'Auto (recommended)',
        desc: 'The panel picks the correct Java for your Minecraft version and server type.',
      },
      { value: 'java8', label: 'Java 8', desc: 'Required for Forge below 1.18 and other very old servers.' },
      { value: 'java16', label: 'Java 16', desc: 'For Minecraft 1.17 (and Paper 1.16.5).' },
      {
        value: 'java17',
        label: 'Java 17',
        desc: 'For Minecraft 1.18 to 1.20.4, and a fallback for some Forge 1.21 mods.',
      },
      { value: 'java21', label: 'Java 21', desc: 'For Minecraft 1.20.5 and later.' },
      { value: 'java25', label: 'Java 25', desc: 'Newest runtime, for the latest Minecraft versions.' },
    ],
    mode: 'advanced',
    section: 'flavor',
    requiresRestart: true,
  },
  {
    key: 'TZ',
    scope: 'env',
    label: 'Time zone',
    help: 'IANA time zone name (for example, Europe/London) so log timestamps and scheduled tasks match your local time. Defaults to UTC.',
    type: 'text',
    default: 'UTC',
    mode: 'advanced',
    section: 'advanced',
    requiresRestart: true,
  },
  {
    key: 'UID',
    scope: 'env',
    label: 'File owner user ID',
    help: 'Linux user ID the server process runs as. The panel sets this to its own user automatically so it can manage the server’s files (mods, backups, deletes); on Linux a value here is overridden. Only relevant on hosts that must pin a specific owner.',
    type: 'number',
    default: 1000,
    min: 0,
    mode: 'advanced',
    section: 'advanced',
    requiresRestart: true,
  },
  {
    key: 'GID',
    scope: 'env',
    label: 'File owner group ID',
    help: 'Linux group ID the server process runs as. Pairs with the user ID above.',
    type: 'number',
    default: 1000,
    min: 0,
    mode: 'advanced',
    section: 'advanced',
    requiresRestart: true,
  },
  {
    key: 'SETUP_ONLY',
    scope: 'env',
    label: 'Setup only (no launch)',
    help: 'Downloads and installs all server files, then exits without starting the server. Useful for pre-provisioning a data directory; the container stops right after setup.',
    type: 'boolean',
    default: false,
    mode: 'advanced',
    section: 'advanced',
    requiresRestart: true,
  },
];
