'use strict';

// Java / JVM tuning flags.

module.exports = [
  {
    key: 'USE_AIKAR_FLAGS',
    scope: 'env',
    label: 'Aikar’s optimization flags',
    help: 'Battle-tested Java garbage-collection tuning that reduces lag spikes on busy servers. Recommended for most servers with 4 GB of RAM or more. Reserves the whole heap the moment the server starts, so memory reads as the full "RAM (Java heap)" value immediately (it would reach that figure within a minute anyway).',
    type: 'boolean',
    default: false,
    mode: 'simple',
    section: 'jvm',
    note: 'Recommended for modded servers',
    conflictsWith: 'USE_MEOWICE_FLAGS',
    requiresRestart: true,
  },
  {
    key: 'USE_MEOWICE_FLAGS',
    scope: 'env',
    label: 'MeowIce’s flags (Java 17+)',
    help: 'A newer alternative to Aikar’s flags tuned for modern Java versions. Pick either this or Aikar’s flags, not both. Like Aikar’s, it reserves the whole heap the moment the server starts.',
    type: 'boolean',
    default: false,
    mode: 'advanced',
    section: 'jvm',
    note: 'Incompatible with Aikar’s flags',
    conflictsWith: 'USE_AIKAR_FLAGS',
    requiresRestart: true,
  },
  {
    key: 'JVM_OPTS',
    scope: 'env',
    label: 'Extra JVM options',
    help: 'Additional options passed straight to the Java command line, space-separated (for example -XX:+UseZGC). These come after the flag presets, so they win over them; -XX:-AlwaysPreTouch here stops Aikar’s or MeowIce’s flags from reserving the whole heap at start. For -X options use the dedicated field below.',
    type: 'text',
    mode: 'advanced',
    section: 'jvm',
    requiresRestart: true,
  },
  {
    key: 'JVM_XX_OPTS',
    scope: 'env',
    label: 'JVM -XX options',
    help: 'Options placed before the memory flags, typically -XX garbage-collector settings. Note that the flag presets are added after these, so a preset’s own setting wins over a conflicting one here; use "Extra JVM options" to override a preset.',
    type: 'text',
    mode: 'advanced',
    section: 'jvm',
    requiresRestart: true,
  },
  {
    key: 'JVM_DD_OPTS',
    scope: 'env',
    label: 'JVM system properties (-D)',
    help: 'Comma or space separated name=value pairs turned into -Dname=value system properties. Example: disable.watchdog:true is needed for auto-pause on Paper servers.',
    type: 'text',
    mode: 'advanced',
    section: 'jvm',
    requiresRestart: true,
  },
  {
    key: 'ENABLE_JMX',
    scope: 'env',
    prop: 'enable-jmx-monitoring',
    label: 'JMX monitoring',
    help: 'Opens a JMX port for attaching Java profilers like VisualVM from another machine. Requires JMX_HOST to be set to the Docker host’s IP.',
    type: 'boolean',
    default: false,
    mode: 'advanced',
    section: 'jvm',
    requiresRestart: true,
  },
];
