'use strict';

// Logs & maintenance: shutdown behavior, logging toggles, and
// server.properties management switches.

module.exports = [
  {
    key: 'STOP_DURATION',
    scope: 'env',
    label: 'Graceful stop timeout',
    help: 'Seconds to wait for the server to save and exit after "stop" is sent. Raise it together with the Docker stop grace period. If the server is force-killed before it finishes saving, give it more time here.',
    type: 'number',
    unit: 'seconds',
    default: 60,
    min: 1,
    mode: 'advanced',
    section: 'maintenance',
    requiresRestart: true,
  },
  {
    key: 'STOP_SERVER_ANNOUNCE_DELAY',
    scope: 'env',
    label: 'Shutdown announce delay',
    help: 'Seconds between announcing the shutdown in-game and actually stopping, so players can wrap up. The Docker stop grace period must be longer than this delay plus save time.',
    type: 'number',
    unit: 'seconds',
    min: 0,
    mode: 'advanced',
    section: 'maintenance',
    requiresRestart: true,
  },
  {
    key: 'ENABLE_ROLLING_LOGS',
    scope: 'env',
    label: 'Rolling log files (legacy)',
    help: 'Legacy switch. Rolling and archived log files are now on by default through the templated logging config. Only relevant for old Minecraft versions where rolling logs conflict with Log4j security patches.',
    type: 'boolean',
    default: false,
    mode: 'advanced',
    section: 'maintenance',
    requiresRestart: true,
  },
  {
    key: 'LOG_TIMESTAMP',
    scope: 'env',
    label: 'Timestamp startup logs',
    help: 'Prefixes the container’s [init] startup log lines with a timestamp. Affects only the image’s setup logs, not the Minecraft server’s own log output.',
    type: 'boolean',
    default: false,
    mode: 'advanced',
    section: 'maintenance',
    requiresRestart: true,
  },
  {
    key: 'SNOOPER_ENABLED',
    scope: 'env',
    prop: 'snooper-enabled',
    label: 'Mojang telemetry (snooper)',
    help: 'Sends usage telemetry to Mojang. This only exists on older Minecraft versions; it was removed in modern ones.',
    type: 'boolean',
    mode: 'advanced',
    section: 'maintenance',
    requiresRestart: true,
  },
  {
    key: 'DUMP_SERVER_PROPERTIES',
    scope: 'env',
    label: 'Dump server.properties to log',
    help: 'Prints the final server.properties contents to the log before the server starts. Handy for debugging why a setting didn’t apply.',
    type: 'boolean',
    default: false,
    mode: 'advanced',
    section: 'maintenance',
    requiresRestart: true,
  },
  {
    key: 'DEBUG',
    scope: 'env',
    label: 'Verbose startup debug',
    help: 'Much more verbose logging of the container’s startup scripts (downloads and installs), not the Minecraft server itself. Turn on when reporting problems.',
    type: 'boolean',
    default: false,
    mode: 'advanced',
    section: 'maintenance',
    requiresRestart: true,
  },
  {
    key: 'OVERRIDE_SERVER_PROPERTIES',
    scope: 'env',
    label: 'Panel manages server.properties',
    help: 'When on (default), server.properties is rewritten from these settings at every start. Turn off only if you want to hand-edit the file. Panel property settings then stop applying.',
    type: 'boolean',
    default: true,
    mode: 'advanced',
    section: 'maintenance',
    danger: true,
    requiresRestart: true,
  },
  {
    key: 'SKIP_SERVER_PROPERTIES',
    scope: 'env',
    label: 'Skip server.properties entirely',
    help: 'Stops the image from creating or touching server.properties at all. This is stronger than the override toggle above; no file is created if it’s missing. Leave off unless something else fully manages the file.',
    type: 'boolean',
    default: false,
    mode: 'advanced',
    section: 'maintenance',
    danger: true,
    requiresRestart: true,
  },
];
