'use strict';

// Networking: host port mappings (panel-managed), query protocol, and
// connection-level tuning. In-container ports stay at their defaults;
// the panel maps them to free host ports.

module.exports = [
  {
    key: 'SERVER_PORT',
    scope: 'env',
    label: 'In-container game port',
    help: 'The port the server binds inside the container. The docs warn that changing it breaks image integrations, so the panel keeps it at 25565 and maps a host port instead.',
    type: 'number',
    default: 25565,
    mode: 'advanced',
    section: 'network',
    hidden: true,
    requiresRestart: true,
  },
  {
    key: 'portGame',
    scope: 'panel',
    label: 'Game port (on this machine)',
    help: 'The host port players connect to; the panel maps it to the container’s internal game port (25565). A free port is suggested automatically, and each server needs its own.',
    type: 'number',
    min: 1024,
    max: 65535,
    mode: 'simple',
    section: 'network',
    requiresRestart: true,
  },
  {
    key: 'portRcon',
    scope: 'panel',
    label: 'RCON port (on this machine)',
    help: 'Host port the panel maps to the container’s RCON port (25575) so it can send commands and stop the server gracefully. Keep it firewalled from the internet: RCON grants full console access.',
    type: 'number',
    min: 1024,
    max: 65535,
    mode: 'advanced',
    section: 'network',
    requiresRestart: true,
  },
  {
    key: 'portBedrock',
    scope: 'panel',
    label: 'Bedrock port (on this machine)',
    help: 'UDP host port mapped for Bedrock clients when a GeyserMC bridge is installed (in-container 19132/udp). Leave empty if you only serve Java Edition players.',
    type: 'number',
    min: 1024,
    max: 65535,
    mode: 'advanced',
    section: 'network',
    note: 'Only needed with GeyserMC',
    requiresRestart: true,
  },
  {
    key: 'ENABLE_QUERY',
    scope: 'env',
    prop: 'enable-query',
    label: 'Query protocol',
    help: 'Enables the GameSpy query protocol so external tools can ask the server for its status and player list. Note: off-box queries hit the game port and will wake an auto-paused server.',
    type: 'boolean',
    default: false,
    mode: 'advanced',
    section: 'network',
    requiresRestart: true,
  },
  {
    key: 'QUERY_PORT',
    scope: 'env',
    label: 'Query port (UDP)',
    help: 'UDP port used by the query protocol inside the container (default 25565). Only relevant when the query protocol is enabled.',
    type: 'number',
    default: 25565,
    min: 1,
    max: 65535,
    mode: 'advanced',
    section: 'network',
    requiresRestart: true,
  },
  {
    key: 'PREVENT_PROXY_CONNECTIONS',
    scope: 'env',
    prop: 'prevent-proxy-connections',
    label: 'Block VPN/proxy players',
    help: 'Kicks players whose connection appears to come through a VPN or proxy.',
    type: 'boolean',
    mode: 'advanced',
    section: 'network',
    requiresRestart: true,
  },
  {
    key: 'NETWORK_COMPRESSION_THRESHOLD',
    scope: 'env',
    prop: 'network-compression-threshold',
    label: 'Packet compression threshold',
    help: 'Packets larger than this many bytes are compressed before sending (vanilla default 256). Use -1 to disable compression or 0 to compress everything. Lower values trade CPU for bandwidth.',
    type: 'number',
    min: -1,
    mode: 'advanced',
    section: 'network',
    requiresRestart: true,
  },
  {
    key: 'USE_NATIVE_TRANSPORT',
    scope: 'env',
    prop: 'use-native-transport',
    label: 'Native network transport',
    help: 'Uses Linux-optimized (epoll) networking for better throughput (vanilla default on). Only turn off to troubleshoot networking issues.',
    type: 'boolean',
    mode: 'advanced',
    section: 'network',
    requiresRestart: true,
  },
];
