'use strict';

// Modpacks & content: CurseForge / Modrinth / FTB installers, individual
// mods and plugins, generic packs, and datapacks. Pack selection vars are
// hidden - the panel's modpack installer UI manages them.

module.exports = [
  // --- CurseForge (AUTO_CURSEFORGE) ---
  {
    key: 'CF_API_KEY',
    scope: 'env',
    label: 'CurseForge API key',
    help: 'Personal API key from console.curseforge.com, required for automated CurseForge modpack installs. Stored once in the panel settings and injected automatically.',
    type: 'password',
    mode: 'advanced',
    section: 'packs',
    hidden: true,
    requiresRestart: true,
  },
  {
    key: 'CF_SLUG',
    scope: 'env',
    label: 'CurseForge modpack slug',
    help: 'The modpack’s slug identifier (e.g. craftoria). Managed by the modpack installer UI.',
    type: 'text',
    mode: 'advanced',
    section: 'packs',
    hidden: true,
    note: 'Managed by the modpack installer UI',
    requiresRestart: true,
  },
  {
    key: 'CF_PAGE_URL',
    scope: 'env',
    label: 'CurseForge modpack page URL',
    help: 'URL of the modpack page (or a specific file page) on curseforge.com. Managed by the modpack installer UI.',
    type: 'text',
    mode: 'advanced',
    section: 'packs',
    hidden: true,
    note: 'Managed by the modpack installer UI',
    requiresRestart: true,
  },
  {
    key: 'CF_FILE_ID',
    scope: 'env',
    label: 'CurseForge file ID',
    help: 'Numeric file ID that pins a specific modpack version instead of the latest. Managed by the modpack installer UI.',
    type: 'number',
    mode: 'advanced',
    section: 'packs',
    hidden: true,
    note: 'Managed by the modpack installer UI',
    requiresRestart: true,
  },
  {
    key: 'CF_FILENAME_MATCHER',
    scope: 'env',
    label: 'CurseForge filename matcher',
    help: 'Substring used to pick the desired modpack file by name. Managed by the modpack installer UI.',
    type: 'text',
    mode: 'advanced',
    section: 'packs',
    hidden: true,
    note: 'Managed by the modpack installer UI',
    requiresRestart: true,
  },
  {
    key: 'CF_EXCLUDE_MODS',
    scope: 'env',
    label: 'Exclude mods',
    help: 'Mods (project slugs or IDs) to skip when installing the modpack. These are typically client-only mods that crash a dedicated server.',
    type: 'list',
    mode: 'advanced',
    section: 'packs',
    requiresRestart: true,
  },
  {
    key: 'CF_FORCE_INCLUDE_MODS',
    scope: 'env',
    label: 'Force-include mods',
    help: 'Mods (slugs or IDs) to install even if an exclusion rule would normally skip them.',
    type: 'list',
    mode: 'advanced',
    section: 'packs',
    requiresRestart: true,
  },
  {
    key: 'CF_EXCLUDE_ALL_MODS',
    scope: 'env',
    label: 'Exclude all mods',
    help: 'Skips installing every mod from the pack; combine with force-include to hand-pick only the mods you want.',
    type: 'boolean',
    mode: 'advanced',
    section: 'packs',
    requiresRestart: true,
  },
  {
    key: 'CF_OVERRIDES_EXCLUSIONS',
    scope: 'env',
    label: 'Exclude override files',
    help: 'Ant-style path patterns for files in the modpack’s overrides that should not be copied onto the server.',
    type: 'list',
    mode: 'advanced',
    section: 'packs',
    requiresRestart: true,
  },
  {
    key: 'CF_IGNORE_MISSING_FILES',
    scope: 'env',
    label: 'Ignore missing pack files',
    help: 'Continues the install even when some files listed by the modpack can’t be downloaded, instead of failing the whole startup.',
    type: 'boolean',
    mode: 'advanced',
    section: 'packs',
    requiresRestart: true,
  },
  {
    key: 'CF_FORCE_SYNCHRONIZE',
    scope: 'env',
    label: 'Re-apply exclude/include rules',
    help: 'Forces the exclusion and inclusion rules to be re-evaluated on the next start. Use it after changing the lists above.',
    type: 'boolean',
    default: false,
    mode: 'advanced',
    section: 'packs',
    requiresRestart: true,
  },
  {
    key: 'CF_PARALLEL_DOWNLOADS',
    scope: 'env',
    label: 'Parallel mod downloads',
    help: 'How many mod files are downloaded at the same time during a modpack install.',
    type: 'number',
    default: 4,
    min: 1,
    mode: 'advanced',
    section: 'packs',
    requiresRestart: true,
  },
  {
    key: 'CF_SET_LEVEL_FROM',
    scope: 'env',
    label: 'Use modpack world',
    help: 'Automatically points the server at world data shipped inside the modpack, either a bundled world file or the pack’s overrides folder.',
    type: 'enum',
    options: [
      { value: 'WORLD_FILE', label: 'Bundled world file' },
      { value: 'OVERRIDES', label: 'World from overrides' },
    ],
    mode: 'advanced',
    section: 'packs',
    requiresRestart: true,
  },

  // --- Modrinth ---
  {
    key: 'MODRINTH_MODPACK',
    scope: 'env',
    label: 'Modrinth modpack',
    help: 'Modrinth project slug, ID, page URL, or .mrpack path/URL to install. Managed by the modpack installer UI.',
    type: 'text',
    mode: 'advanced',
    section: 'packs',
    hidden: true,
    note: 'Managed by the modpack installer UI',
    requiresRestart: true,
  },
  {
    key: 'MODRINTH_VERSION',
    scope: 'env',
    label: 'Modrinth modpack version',
    help: 'Version ID or number that pins a specific modpack release. Managed by the modpack installer UI.',
    type: 'text',
    mode: 'advanced',
    section: 'packs',
    hidden: true,
    note: 'Managed by the modpack installer UI',
    requiresRestart: true,
  },
  {
    key: 'MODRINTH_MODPACK_VERSION_TYPE',
    scope: 'env',
    label: 'Modrinth release channel',
    help: 'Which release channel to accept when resolving the latest modpack version: stable releases only, or also beta/alpha builds.',
    type: 'enum',
    options: [
      { value: 'release', label: 'Release' },
      { value: 'beta', label: 'Beta' },
      { value: 'alpha', label: 'Alpha' },
    ],
    mode: 'advanced',
    section: 'packs',
    requiresRestart: true,
  },
  {
    key: 'MODRINTH_EXCLUDE_FILES',
    scope: 'env',
    label: 'Exclude pack files',
    help: 'Files from the Modrinth pack to skip installing. These are typically client-only mods that crash a dedicated server.',
    type: 'list',
    mode: 'advanced',
    section: 'packs',
    requiresRestart: true,
  },
  {
    key: 'MODRINTH_FORCE_INCLUDE_FILES',
    scope: 'env',
    label: 'Force-include pack files',
    help: 'Files to install even if an exclusion rule would normally skip them.',
    type: 'list',
    mode: 'advanced',
    section: 'packs',
    requiresRestart: true,
  },
  {
    key: 'MODRINTH_IGNORE_MISSING_FILES',
    scope: 'env',
    label: 'Ignore missing pack files',
    help: 'Continues the install even when some files listed by the pack can’t be downloaded.',
    type: 'boolean',
    mode: 'advanced',
    section: 'packs',
    requiresRestart: true,
  },
  {
    key: 'MODRINTH_FORCE_SYNCHRONIZE',
    scope: 'env',
    label: 'Re-apply exclude/include rules',
    help: 'Forces the Modrinth exclusion and inclusion rules to be re-evaluated on the next start.',
    type: 'boolean',
    mode: 'advanced',
    section: 'packs',
    requiresRestart: true,
  },
  {
    key: 'MODRINTH_PROJECTS',
    scope: 'env',
    label: 'Individual Modrinth mods/plugins',
    help: 'Modrinth projects to download individually, outside any modpack, for example fabric-api. One slug or ID per line.',
    type: 'list',
    mode: 'advanced',
    section: 'packs',
    requiresRestart: true,
  },

  // --- FTB ---
  {
    key: 'FTB_MODPACK_ID',
    scope: 'env',
    label: 'FTB modpack ID',
    help: 'Numeric Feed the Beast modpack ID. Managed by the modpack installer UI.',
    type: 'number',
    mode: 'advanced',
    section: 'packs',
    hidden: true,
    note: 'Managed by the modpack installer UI',
    requiresRestart: true,
  },
  {
    key: 'FTB_MODPACK_VERSION_ID',
    scope: 'env',
    label: 'FTB modpack version ID',
    help: 'Pins a specific FTB pack version; latest when unset. Managed by the modpack installer UI.',
    type: 'number',
    mode: 'advanced',
    section: 'packs',
    hidden: true,
    note: 'Managed by the modpack installer UI',
    requiresRestart: true,
  },

  // --- Individual content ---
  {
    key: 'CURSEFORGE_FILES',
    scope: 'env',
    label: 'Individual CurseForge files',
    help: 'Individual CurseForge mods or plugins to download outside a modpack, one reference per line. Requires the CurseForge API key.',
    type: 'list',
    mode: 'advanced',
    section: 'packs',
    requiresRestart: true,
  },
  {
    key: 'MODS',
    scope: 'env',
    label: 'Mod downloads',
    help: 'Mod jars to install: URLs, container paths, or directories of jars, one per line. Entries removed from this list are also removed from disk. An empty list deletes all managed mods.',
    type: 'list',
    mode: 'advanced',
    section: 'packs',
    requiresRestart: true,
  },
  {
    key: 'PLUGINS',
    scope: 'env',
    label: 'Plugin downloads',
    help: 'Plugin jars to install on Paper/Spigot-family servers: URLs, container paths, or directories, one per line. Entries removed from the list are removed from disk too.',
    type: 'list',
    mode: 'advanced',
    section: 'packs',
    requiresRestart: true,
  },
  {
    key: 'MODS_FILE',
    scope: 'env',
    label: 'Mods list file',
    help: 'URL or container path of a text file listing one mod URL per line (# comments allowed). Useful for sharing one mod list across servers.',
    type: 'text',
    mode: 'advanced',
    section: 'packs',
    requiresRestart: true,
  },
  {
    key: 'SPIGET_RESOURCES',
    scope: 'env',
    label: 'Spigot plugins (Spiget IDs)',
    help: 'SpigotMC resource IDs to auto-download as plugins via the Spiget API. Only the numeric ID from the plugin’s page URL is needed.',
    type: 'list',
    mode: 'advanced',
    section: 'packs',
    requiresRestart: true,
  },

  // --- Generic packs & datapacks ---
  {
    key: 'GENERIC_PACK',
    scope: 'env',
    label: 'Generic content pack',
    help: 'URL or container path of a zip/tgz containing arbitrary server content (mods, plugins, configs) to unpack over the server folder. Also handy for CurseForge packs without an installer.',
    type: 'text',
    mode: 'advanced',
    section: 'packs',
    requiresRestart: true,
  },
  {
    key: 'GENERIC_PACKS',
    scope: 'env',
    label: 'Generic content packs (multiple)',
    help: 'Several archives applied in order, comma separated. The prefix and suffix fields below are added around each entry. Useful for building CDN URLs.',
    type: 'list',
    mode: 'advanced',
    section: 'packs',
    requiresRestart: true,
  },
  {
    key: 'GENERIC_PACKS_PREFIX',
    scope: 'env',
    label: 'Generic packs URL prefix',
    help: 'Text prepended to every entry in the generic packs list, e.g. a base URL.',
    type: 'text',
    mode: 'advanced',
    section: 'packs',
    requiresRestart: true,
  },
  {
    key: 'GENERIC_PACKS_SUFFIX',
    scope: 'env',
    label: 'Generic packs URL suffix',
    help: 'Text appended to every entry in the generic packs list, e.g. ".zip".',
    type: 'text',
    mode: 'advanced',
    section: 'packs',
    requiresRestart: true,
  },
  {
    key: 'DATAPACKS',
    scope: 'env',
    label: 'Datapacks',
    help: 'Datapack zips to install into the world’s datapacks folder: URLs, container paths, or directories, one per line.',
    type: 'list',
    mode: 'advanced',
    section: 'packs',
    requiresRestart: true,
  },
  {
    key: 'VANILLATWEAKS_SHARECODE',
    scope: 'env',
    label: 'VanillaTweaks share codes',
    help: 'Share codes from vanillatweaks.net whose datapacks and crafting tweaks are installed into the world automatically. Old versions are cleaned up on update.',
    type: 'list',
    mode: 'advanced',
    section: 'packs',
    requiresRestart: true,
  },
  {
    key: 'VANILLATWEAKS_FILE',
    scope: 'env',
    label: 'VanillaTweaks spec file',
    help: 'Container path or URL of a VanillaTweaks JSON spec file, as an alternative to share codes.',
    type: 'text',
    mode: 'advanced',
    section: 'packs',
    requiresRestart: true,
  },

  // --- GT New Horizons ---
  {
    key: 'GTNH_PACK_VERSION',
    scope: 'env',
    label: 'GTNH pack version',
    help: 'The exact GT New Horizons release to install. Managed by the modpack installer. The panel always pins a concrete version so restarts never upgrade the pack behind your back.',
    type: 'text',
    mode: 'advanced',
    section: 'packs',
    hidden: true,
    note: 'Managed by the modpack installer UI',
    requiresRestart: true,
  },
  {
    key: 'SKIP_GTNH_UPDATE_CHECK',
    scope: 'env',
    label: 'Skip the image’s GTNH update check',
    help: 'Stops the container comparing the installed pack against GTNH_PACK_VERSION on boot. Leave off: the check also runs the installer, so skipping it on a server whose pack has not installed yet means the pack never downloads and the server crash-loops on missing files. The pinned version already prevents surprise upgrades.',
    type: 'boolean',
    default: false,
    mode: 'advanced',
    section: 'packs',
    requiresRestart: true,
  },
  {
    key: 'GTNH_DELETE_BACKUPS',
    scope: 'env',
    label: 'Delete GTNH’s own backups on update',
    help: 'Removes the backup copies the GTNH updater leaves behind in the server folder. The panel takes its own backups before any pack upgrade, so this mainly saves disk.',
    type: 'boolean',
    default: false,
    mode: 'advanced',
    section: 'packs',
    requiresRestart: true,
  },

  // --- Dangerous cleanup ---
  {
    key: 'REMOVE_OLD_MODS',
    scope: 'env',
    label: 'Wipe mods before install',
    help: 'Deletes the entire mods (or plugins) folder before installing new content. The panel never sets this: it wipes the whole mods folder, including anything added by hand.',
    type: 'boolean',
    mode: 'advanced',
    section: 'packs',
    hidden: true,
    danger: true,
    note: 'Never set by the panel. Wipes the whole mods folder.',
    requiresRestart: true,
  },
];
