'use strict';

// Players: whitelist and operator provisioning.

module.exports = [
  {
    key: 'WHITELIST',
    scope: 'env',
    label: 'Whitelisted players',
    help: 'Player names (or UUIDs) allowed to join. Setting any names automatically turns whitelisting on; names are resolved to UUIDs via a player-lookup API at startup.',
    type: 'list',
    mode: 'simple',
    section: 'players',
    requiresRestart: true,
  },
  {
    key: 'WHITELIST_FILE',
    scope: 'env',
    label: 'Whitelist file URL / path',
    help: 'URL or container path of a whitelist.json to install. Cannot be combined with the MERGE mode below; by default it replaces the existing file and then the player list above is merged in.',
    type: 'text',
    mode: 'advanced',
    section: 'players',
    requiresRestart: true,
  },
  {
    key: 'EXISTING_WHITELIST_FILE',
    scope: 'env',
    label: 'Existing whitelist handling',
    help: 'What to do when a whitelist file already exists on the server: leave it alone, overwrite it to match your settings, or merge new players into it.',
    type: 'enum',
    default: 'SYNC_FILE_MERGE_LIST',
    options: [
      { value: 'SKIP', label: 'Skip', desc: 'Leave the existing file untouched.' },
      { value: 'SYNCHRONIZE', label: 'Synchronize', desc: 'Make the file exactly match the configured players/file.' },
      { value: 'MERGE', label: 'Merge', desc: 'Add configured players into the existing file (file URL not allowed).' },
      {
        value: 'SYNC_FILE_MERGE_LIST',
        label: 'Sync file, merge list',
        desc: 'Whitelist file replaces the existing one, then listed players are merged in.',
      },
    ],
    mode: 'advanced',
    section: 'players',
    requiresRestart: true,
  },
  {
    key: 'ENFORCE_WHITELIST',
    scope: 'env',
    prop: 'enforce-whitelist',
    label: 'Enforce whitelist changes',
    help: 'Immediately kicks online players who are removed from the whitelist, instead of waiting until they reconnect.',
    type: 'boolean',
    default: false,
    mode: 'advanced',
    section: 'players',
    requiresRestart: true,
  },
  {
    key: 'ENABLE_WHITELIST',
    scope: 'env',
    prop: 'white-list',
    label: 'Whitelist on (manual file)',
    help: 'Turns whitelisting on when you manage the whitelist file yourself. Not needed if you list players above, which enables the whitelist automatically.',
    type: 'boolean',
    default: false,
    mode: 'advanced',
    section: 'players',
    requiresRestart: true,
  },
  {
    key: 'OPS',
    scope: 'env',
    label: 'Operators (admins)',
    help: 'Player names (or UUIDs) given operator/admin rights at startup. Operators can run server commands in-game, so grant this sparingly.',
    type: 'list',
    mode: 'advanced',
    section: 'players',
    requiresRestart: true,
  },
  {
    key: 'OPS_FILE',
    scope: 'env',
    label: 'Ops file URL / path',
    help: 'URL or container path of an ops.json to install into the standard location. Cannot be combined with the MERGE mode below.',
    type: 'text',
    mode: 'advanced',
    section: 'players',
    requiresRestart: true,
  },
  {
    key: 'EXISTING_OPS_FILE',
    scope: 'env',
    label: 'Existing ops handling',
    help: 'What to do when an ops file already exists: leave it, overwrite it to match your settings (existing permission levels are kept), or merge new operators into it.',
    type: 'enum',
    default: 'SYNC_FILE_MERGE_LIST',
    options: [
      { value: 'SKIP', label: 'Skip', desc: 'Leave the existing file untouched.' },
      {
        value: 'SYNCHRONIZE',
        label: 'Synchronize',
        desc: 'Make the file match the configured ops; keeps each player’s level.',
      },
      { value: 'MERGE', label: 'Merge', desc: 'Add configured ops into the existing file (file URL not allowed).' },
      {
        value: 'SYNC_FILE_MERGE_LIST',
        label: 'Sync file, merge list',
        desc: 'Ops file replaces the existing one, then listed ops are merged in.',
      },
    ],
    mode: 'advanced',
    section: 'players',
    requiresRestart: true,
  },
];
