'use strict';

// RCON & console: the remote-console protocol the panel depends on, plus
// automatic command hooks.

module.exports = [
  {
    key: 'ENABLE_RCON',
    scope: 'env',
    label: 'RCON enabled',
    help: 'The remote-console protocol used for graceful shutdown, backups, and the interactive console. The panel needs it to stop the server cleanly and send commands, so leave it on.',
    type: 'boolean',
    default: true,
    mode: 'advanced',
    section: 'rcon',
    note: 'Required for panel commands & graceful stop',
    requiresRestart: true,
  },
  {
    key: 'RCON_PASSWORD',
    scope: 'env',
    label: 'RCON password',
    help: 'Authentication password for RCON. If unset, the image generates a new random one on every start, so the panel generates a secure password once and stores it itself.',
    type: 'password',
    mode: 'advanced',
    section: 'rcon',
    hidden: true,
    requiresRestart: true,
  },
  {
    key: 'RCON_PORT',
    scope: 'env',
    label: 'In-container RCON port',
    help: 'Port the server listens on for RCON inside the container. The docs warn that changing it breaks the image’s graceful-stop and health checks, so the panel keeps it at 25575.',
    type: 'number',
    default: 25575,
    mode: 'advanced',
    section: 'rcon',
    hidden: true,
    requiresRestart: true,
  },
  {
    key: 'BROADCAST_RCON_TO_OPS',
    scope: 'env',
    prop: 'broadcast-rcon-to-ops',
    label: 'Show RCON output to ops',
    help: 'Broadcasts the output of RCON-issued commands to online operators. With a panel sending frequent commands, leaving this off avoids chat spam for your ops.',
    type: 'boolean',
    default: false,
    mode: 'advanced',
    section: 'rcon',
    requiresRestart: true,
  },
  {
    key: 'RCON_CMDS_STARTUP',
    scope: 'env',
    label: 'Commands on server start',
    help: 'Console commands run automatically each time the server starts, one per line. Handy for setting gamerules. The leading / is optional.',
    type: 'list',
    mode: 'advanced',
    section: 'rcon',
    requiresRestart: true,
  },
  {
    key: 'RCON_CMDS_ON_CONNECT',
    scope: 'env',
    label: 'Commands when a player joins',
    help: 'Console commands run whenever any player connects, one per line. The hook doesn’t know who joined, so use selector-based commands like @a[team=] to target players.',
    type: 'list',
    mode: 'advanced',
    section: 'rcon',
    requiresRestart: true,
  },
  {
    key: 'RCON_CMDS_FIRST_CONNECT',
    scope: 'env',
    label: 'Commands when server becomes occupied',
    help: 'Console commands run when the first player joins an empty server. For example, pausing chunk pre-generation while people are online.',
    type: 'list',
    mode: 'advanced',
    section: 'rcon',
    requiresRestart: true,
  },
  {
    key: 'RCON_CMDS_ON_DISCONNECT',
    scope: 'env',
    label: 'Commands when a player leaves',
    help: 'Console commands run whenever any player disconnects, one per line.',
    type: 'list',
    mode: 'advanced',
    section: 'rcon',
    requiresRestart: true,
  },
  {
    key: 'RCON_CMDS_LAST_DISCONNECT',
    scope: 'env',
    label: 'Commands when server becomes empty',
    help: 'Console commands run when the last player leaves. For example, cleaning up dropped items or resuming chunk pre-generation.',
    type: 'list',
    mode: 'advanced',
    section: 'rcon',
    requiresRestart: true,
  },
  {
    key: 'CREATE_CONSOLE_IN_PIPE',
    scope: 'env',
    label: 'Console input pipe',
    help: 'Creates a stdin pipe so console commands can still be sent (via mc-send-to-console) when RCON is disabled. Only needed as a fallback.',
    type: 'boolean',
    mode: 'advanced',
    section: 'rcon',
    requiresRestart: true,
  },
];
