'use strict';

// Resources: the two memory layers, CPU, and the panel-enforced disk quota.

module.exports = [
  {
    key: 'MEMORY',
    scope: 'env',
    label: 'RAM (Java heap)',
    help: 'Memory the Minecraft/Java process may use. The image hands this to Java as both the starting and the maximum heap, so a running server settles at this figure within its first minute and stays there even when nobody is playing. That is Java keeping what it was given, not a leak. Modpacks usually need 4 GB or more; the image default of 1 GB is only enough for small vanilla servers.',
    type: 'size-mb',
    unit: 'MB',
    default: 1024,
    min: 512,
    max: 65536,
    step: 512,
    mode: 'simple',
    section: 'resources',
    requiresRestart: true,
  },
  {
    key: 'INIT_MEMORY',
    scope: 'env',
    label: 'Initial heap (advanced)',
    help: 'Sets a smaller starting heap than the maximum, so memory use grows with the world instead of sitting at the full heap from the start. Measured on a 2 GB heap: 512 MB here brought idle use from 2.6 GB down to about 1.3 GB. Leave empty to let "RAM (Java heap)" control both, which is what Aikar’s flags recommend for the steadiest performance.',
    type: 'size-mb',
    unit: 'MB',
    min: 512,
    max: 65536,
    step: 512,
    mode: 'advanced',
    section: 'resources',
    requiresRestart: true,
  },
  {
    key: 'MAX_MEMORY',
    scope: 'env',
    label: 'Maximum heap (advanced)',
    help: 'Sets a different maximum heap than the initial one. Leave empty to let "RAM (Java heap)" control both.',
    type: 'size-mb',
    unit: 'MB',
    min: 512,
    max: 65536,
    step: 512,
    mode: 'advanced',
    section: 'resources',
    requiresRestart: true,
  },
  {
    key: 'memory',
    scope: 'docker',
    label: 'Container memory limit',
    help: 'The hard memory limit Docker enforces on the whole container. Keep it 25 to 50 percent above the Java heap: Java needs extra room beyond the heap, and if the server reaches this limit it is stopped instantly for running out of memory.',
    type: 'size-mb',
    unit: 'MB',
    default: 6144,
    min: 1024,
    max: 262144,
    step: 512,
    mode: 'simple',
    section: 'resources',
    requiresRestart: true,
  },
  {
    key: 'memorySwap',
    scope: 'docker',
    label: 'Container swap limit',
    help: 'Extra swap space the container may use beyond its memory limit. 0 disables swap. Swapping a Minecraft server causes heavy lag, so leave it at 0 unless you know you need it.',
    type: 'size-mb',
    unit: 'MB',
    default: 0,
    min: 0,
    max: 65536,
    step: 512,
    mode: 'advanced',
    section: 'resources',
    requiresRestart: true,
  },
  {
    key: 'cpus',
    scope: 'docker',
    label: 'CPU limit',
    help: 'How many host CPU cores the server may use (Docker NanoCpus). 0 means unlimited. When a server hits its cap it slows down (tick lag) rather than being killed.',
    type: 'range',
    unit: 'cores',
    default: 0,
    min: 0,
    max: 64,
    step: 0.5,
    mode: 'simple',
    section: 'resources',
    requiresRestart: true,
  },
  {
    key: 'diskQuotaGb',
    scope: 'panel',
    label: 'Disk quota',
    help: 'A limit on this server’s folder size, enforced by the panel itself, since Docker cannot limit disk use for this kind of storage. Over quota, actions that would grow the disk, like mod installs and backups, are blocked until space is freed.',
    type: 'range',
    unit: 'GB',
    default: 25,
    min: 0,
    max: 2048,
    step: 5,
    mode: 'simple',
    section: 'resources',
  },
  {
    key: 'quotaStrict',
    scope: 'panel',
    label: 'Strict quota mode',
    help: 'When usage exceeds the quota by more than 10%, gracefully stop the server automatically. Protects the host from runaway world or log growth; the stop is recorded in history.',
    type: 'boolean',
    default: false,
    mode: 'advanced',
    section: 'resources',
  },
];
