'use strict';

// World: save selection, generation, distances, and world-level toggles.

module.exports = [
  {
    key: 'LEVEL',
    scope: 'env',
    prop: 'level-name',
    label: 'World save name',
    help: 'Name of the world save directory inside the server folder. Change it to switch between saves. The old world stays on disk under its own name.',
    type: 'text',
    default: 'world',
    mode: 'advanced',
    section: 'world',
    requiresRestart: true,
  },
  {
    key: 'SEED',
    scope: 'env',
    prop: 'level-seed',
    label: 'World seed',
    help: 'Seed used when generating a new world. Only affects worlds that have not been created yet. It does nothing to an existing world.',
    type: 'text',
    mode: 'simple',
    section: 'world',
    requiresRestart: true,
  },
  {
    key: 'LEVEL_TYPE',
    scope: 'env',
    prop: 'level-type',
    label: 'World type',
    help: 'World generator preset used when a new world is created. Pair Superflat with generator settings below to customize the layers.',
    type: 'enum',
    options: [
      { value: 'DEFAULT', label: 'Default', desc: 'Standard terrain generation.' },
      { value: 'FLAT', label: 'Superflat', desc: 'Flat world; customize layers via generator settings.' },
      { value: 'LARGEBIOMES', label: 'Large biomes', desc: 'Same terrain, but each biome is much bigger.' },
      { value: 'AMPLIFIED', label: 'Amplified', desc: 'Extreme mountains; needs a beefy server.' },
    ],
    mode: 'advanced',
    section: 'world',
    requiresRestart: true,
  },
  {
    key: 'GENERATOR_SETTINGS',
    scope: 'env',
    prop: 'generator-settings',
    label: 'Generator settings (JSON)',
    help: 'JSON options that customize world generation for certain world types. For Superflat, this is the layer list and biome. Layers apply bottom-up from Y=-64.',
    type: 'text',
    mode: 'advanced',
    section: 'world',
    requiresRestart: true,
  },
  {
    key: 'WORLD',
    scope: 'env',
    label: 'World download URL / path',
    help: 'URL of a zip/tar archive (or a container path) containing an existing world to import. It is only copied in if the world does not already exist. See "Force world copy" to overwrite.',
    type: 'text',
    mode: 'advanced',
    section: 'world',
    requiresRestart: true,
  },
  {
    key: 'FORCE_WORLD_COPY',
    scope: 'env',
    label: 'Force world copy',
    help: 'Re-copies the imported world over the existing one on every start. Leaving this on permanently wipes player progress at each restart. Enable it once to reset, then turn it back off.',
    type: 'boolean',
    default: false,
    mode: 'advanced',
    section: 'world',
    danger: true,
    requiresRestart: true,
  },
  {
    key: 'SPAWN_PROTECTION',
    scope: 'env',
    prop: 'spawn-protection',
    label: 'Spawn protection radius',
    help: 'Radius in blocks around spawn that only operators can modify. 0 disables protection; the vanilla default is 16.',
    type: 'number',
    min: 0,
    mode: 'advanced',
    section: 'world',
    requiresRestart: true,
  },
  {
    key: 'VIEW_DISTANCE',
    scope: 'env',
    prop: 'view-distance',
    label: 'View distance',
    help: 'How many chunks around each player the server sends to their client (vanilla default 10). One of the biggest levers for RAM, CPU, and bandwidth. Lower it if the server lags.',
    type: 'number',
    unit: 'chunks',
    min: 3,
    max: 32,
    mode: 'simple',
    section: 'world',
    requiresRestart: true,
  },
  {
    key: 'SIMULATION_DISTANCE',
    scope: 'env',
    prop: 'simulation-distance',
    label: 'Simulation distance',
    help: 'How many chunks around each player actually tick: mobs, crops, machines (vanilla default 10). A big performance lever alongside view distance.',
    type: 'number',
    unit: 'chunks',
    min: 3,
    max: 32,
    mode: 'advanced',
    section: 'world',
    requiresRestart: true,
  },
  {
    key: 'MAX_WORLD_SIZE',
    scope: 'env',
    prop: 'max-world-size',
    label: 'World border radius',
    help: 'Maximum world border radius in blocks (vanilla default 29,999,984). Useful to cap disk usage from exploration.',
    type: 'number',
    unit: 'blocks',
    min: 1,
    max: 29999984,
    mode: 'advanced',
    section: 'world',
    requiresRestart: true,
  },
  {
    key: 'ALLOW_NETHER',
    scope: 'env',
    prop: 'allow-nether',
    label: 'Allow the Nether',
    help: 'Lets players travel to the Nether dimension through portals.',
    type: 'boolean',
    mode: 'advanced',
    section: 'world',
    requiresRestart: true,
  },
  {
    key: 'GENERATE_STRUCTURES',
    scope: 'env',
    prop: 'generate-structures',
    label: 'Generate structures',
    help: 'Generates villages, strongholds, and other structures in new chunks.',
    type: 'boolean',
    mode: 'advanced',
    section: 'world',
    requiresRestart: true,
  },
  {
    key: 'SPAWN_ANIMALS',
    scope: 'env',
    prop: 'spawn-animals',
    label: 'Spawn animals',
    help: 'Lets passive animals spawn naturally. Recent Minecraft versions moved this to a gamerule and no longer read this property.',
    type: 'boolean',
    mode: 'advanced',
    section: 'world',
    requiresRestart: true,
  },
  {
    key: 'SPAWN_MONSTERS',
    scope: 'env',
    prop: 'spawn-monsters',
    label: 'Spawn monsters',
    help: 'Lets hostile mobs spawn naturally at night and in the dark.',
    type: 'boolean',
    mode: 'advanced',
    section: 'world',
    requiresRestart: true,
  },
  {
    key: 'SPAWN_NPCS',
    scope: 'env',
    prop: 'spawn-npcs',
    label: 'Spawn villagers',
    help: 'Lets villagers spawn. Recent Minecraft versions no longer read this property.',
    type: 'boolean',
    mode: 'advanced',
    section: 'world',
    requiresRestart: true,
  },
  {
    key: 'HARDCORE',
    scope: 'env',
    prop: 'hardcore',
    label: 'Hardcore mode',
    help: 'On death, players are switched to spectator mode instead of respawning. Difficulty is locked to hard.',
    type: 'boolean',
    mode: 'advanced',
    section: 'world',
    danger: true,
    requiresRestart: true,
  },
  {
    key: 'ENABLE_COMMAND_BLOCK',
    scope: 'env',
    prop: 'enable-command-block',
    label: 'Enable command blocks',
    help: 'Allows command blocks to run their commands. Required by many adventure maps and some datapacks.',
    type: 'boolean',
    mode: 'advanced',
    section: 'world',
    requiresRestart: true,
  },
];
